/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import arquivos.Alerta;
import arquivos.Usuario;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author francisco.freire
 */
public class GerirAlertas extends JDialog {

    public ArrayList<Alerta> alertas = new ArrayList<Alerta>();
    private Usuario usuario;

    public ArrayList<Alerta> getAlertas() {
        return alertas;
    }

    public void setAlertas(ArrayList<Alerta> alertas) {
        this.alertas = alertas;
    }

    private Frame owner;

    /**
     * Creates new form GerirAlertas
     */
    public GerirAlertas(Frame owner, String title, boolean modal, Usuario usuario) {
        super(owner, title, modal);
        this.owner = owner;
        this.usuario = usuario;
        initComponents();
    }

    public GerirAlertas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBAlertas = new javax.swing.JComboBox<>();
        jBCriarNovo = new javax.swing.JButton();
        jBApagar = new javax.swing.JButton();
        jBOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBCriarNovo.setText("Criar Novo");
        jBCriarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCriarNovoActionPerformed(evt);
            }
        });

        jBApagar.setText("Apagar");
        jBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarActionPerformed(evt);
            }
        });

        jBOK.setText("OK");
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBOK)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCBAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBCriarNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBApagar))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jCBAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCriarNovo)
                    .addComponent(jBApagar))
                .addGap(67, 67, 67)
                .addComponent(jBOK)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Alerta> carregarAlertas(Usuario usuario) {
        File arquivo = new File("alertas.dat");
        ArrayList<Alerta> Alertas = null;
        try {
            FileInputStream fin = new FileInputStream(arquivo);
            ObjectInputStream oin = new ObjectInputStream(fin);

            //ler objetos de um arquivo
            ArrayList<Alerta> alertasFile = new ArrayList<Alerta>();
            alertasFile = (ArrayList<Alerta>) oin.readObject();

            oin.close(); //fechar o fluxo de entrada
            fin.close(); //fechar arquivo

            Alertas = new ArrayList<Alerta>();
            for (Alerta alerta : alertasFile) {
                if (alerta.getLoginUsuario().equals(usuario.getLogin())) {
                    Alertas.add(alerta);
                }
            }
            //this.Alertas = alertasFile;

            //processaAlertas();
            //System.out.println("tamanho array: " + alertasFile.size());
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("erro: " + ex.toString());
        }
        return Alertas;
    }

    private void salvarAlertas(ArrayList<Alerta> Alertas) {

        File arquivo = new File("alertas.dat");

        try {
            FileOutputStream fout = new FileOutputStream(arquivo);
            ObjectOutputStream oos = new ObjectOutputStream(fout);

            //gravando o alerta no arquivo chamado "alertas.dat"
            oos.writeObject(Alertas);

            oos.flush(); //limpando os dados em buffer
            oos.close(); // fechando fluxo de saída
            fout.close(); // fechando arquivo
            //JOptionPane.showMessageDialog(this, "Arquivo salvo");
        } catch (IOException ex) {
            System.err.println("erro: " + ex.toString());
        }

    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        alertas = carregarAlertas(this.usuario);
        atualizaAlertas();
    }//GEN-LAST:event_formWindowActivated

    private void atualizaAlertas() {
        jCBAlertas.removeAllItems();

        for (Alerta alerta : alertas) {
            jCBAlertas.addItem(alerta.getTipoAlertaDescricao());

        }
    }
    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        // TODO add your handling code here:
        salvarAlertas(alertas);        
        dispose();
    }//GEN-LAST:event_jBOKActionPerformed

    private void jBCriarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCriarNovoActionPerformed
        // TODO add your handling code here:
        CadastrarAlerta cadastrarAlerta = new CadastrarAlerta(this.owner, "Criar Alerta", rootPaneCheckingEnabled
        );
        //this.setEnabled(false);
        cadastrarAlerta.setVisible(true);

        if (cadastrarAlerta.getAlerta() != null) {
            if (alertas == null) {
                alertas = new ArrayList<Alerta>();
            }
            Alerta alertaCriado = cadastrarAlerta.getAlerta();
            alertaCriado.setLoginUsuario(usuario.getLogin());
            alertas.add(cadastrarAlerta.getAlerta());
        }

        salvarAlertas(alertas);
        atualizaAlertas();
    }//GEN-LAST:event_jBCriarNovoActionPerformed

    private void jBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarActionPerformed
        // TODO add your handling code here:
        if (alertas.size() > 0) {
            alertas.remove(jCBAlertas.getSelectedIndex());
            salvarAlertas(alertas);
            atualizaAlertas();
        }
    }//GEN-LAST:event_jBApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerirAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerirAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerirAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerirAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerirAlertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBApagar;
    private javax.swing.JButton jBCriarFiltros;
    private javax.swing.JButton jBCriarNovo;
    private javax.swing.JButton jBOK;
    private javax.swing.JComboBox<String> jCBAlertas;
    // End of variables declaration//GEN-END:variables
}
